# This configuration will be used by a manual AppVeyor build used:
# Build the tools
# Deploy to GitHub releases
# Deploy to NuGet

image: Visual Studio 2017

platform: Any CPU
configuration: Release

shallow_clone: true
skip_tags: true

environment:
  GITHUB_AUTH_TOKEN:
    secure: e24gj/T2VZ5R4XwbNUwj+eu4FbHEqWKUhuvNKXcp4dRPxj8lgW3AbWgSitK5kzek

init:
  - ps: |
      If (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
        $env:IS_NOT_PR = "true"
      }

before_build:
  - nuget restore src\FieldDataFramework.sln

build:
  project: src\FieldDataFramework.sln

after_build:
  - nuget pack src\Aquarius.FieldDataFramework.nuspec

artifacts:
  - path: src\Library
    name: FieldDataPluginFramework
    type: zip
  
  - path: src\FieldDataPluginTool\bin\Release
    name: FieldDataPluginTool
    type: zip
  
  - path: src\PluginPackager\bin\Release
    name: PluginPackager
    type: zip

  - path: src\PluginTester\bin\Release
    name: PluginTester
    type: zip

  - path: 'Aquarius.FieldDataFramework.*.nupkg'
    name: AllPackages
    type: NuGetPackage

deploy:
  - provider: GitHub
    tag: v$(APPVEYOR_BUILD_VERSION)
    release: AQUARIUS Field Data Framework $(APPVEYOR_BUILD_VERSION)
    description: ''
    artifact: FieldDataPluginFramework,FieldDataPluginTool,PluginPackager,PluginTester
    auth_token: $(GITHUB_AUTH_TOKEN)
    on:
      is_not_pr: true

  - provider: NuGet
    api_key:
      secure: 2ysF04mVlBnibe56a/2jETvgEkTCV/ReYVdG8SmlKdlziv7STEEMYtenRU/jDyEa
    skip_symbols: false
    artifact: AllPackages
