# Use goofy versions for PR builds, since PR builds should never yield a sane looking version
version: 127.127.{build}

pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017

platform: Any CPU
configuration: Release

shallow_clone: true
skip_tags: true

before_build:
  - nuget restore src\FieldDataFramework.sln

build:
  project: src\FieldDataFramework.sln
